### ISSUE TITLE
Nhận ý kiến đóng góp

### ISSUE THREAD

**Issue by baolongnguyenmac** [baolongnguyenmac/DataScienceProject#1]
- Xin chào, issue này được nhóm tớ mở ra để nhận ý kiến đóng góp về đồ án.
- Tóm tắt:
  - Đồ án này nhằm dự đoán giá chứng khoán trong khoảng thời gian n ngày tiếp theo
  - Cụ thể, nhóm dự đoán 1 ngày tiếp theo và 30 ngày tiếp theo
  - Hiện tại, đồ án còn 1 phần chưa hoàn thành (chọn tham số tối ưu nhất cho model)
  - Chi tiết hơn có thể xem tại file `ReadMe.md` và cụ thể từng file `*.ipynb`
- Thank you ~~

**Comment by haminhtoan123** [comment]
- Xin chào, mình xin phép được đóng góp ý kiến vào đồ án.
- Ở phần plot đồ thị: mình nghĩ các bạn nên thay "val" bằng "actual", mình nghĩ ý của các bạn là **value** nhưng lúc mới đọc thì mình hiểu nhầm thành **validation**
- Ở phần kết luận với tập test, mình nghĩ các bạn nên dùng **R-squared** để kết luận để có cái nhìn tốt hơn về mô hình tìm được thay vì **mse**

**Comment by PhamVietXuan** [comment]
Xin chào bạn, trước hết thì mình thấy nhóm bạn làm rất tốt vì đã dùng những kiến thức mới và cũng rất phù hợp với bộ dữ liệu trên. Ngay cả việc trực quan hóa kết quả các bạn cũng đã làm rất tốt. Nhưng mình thấy trong phần fit model ở file predict30Days, bạn có dùng epoch = 1 trong khi trước đó ở predict1Days bạn có bước tìm epochs cho mô hình tốt nhất, tại sao qua bên kia bạn không sử dụng lại hoặc tìm lại, chỗ đó mình hơi thắc mắc.

**Comment by baolongnguyenmac** [comment]
> * Xin chào, mình xin phép được đóng góp ý kiến vào đồ án.
> * Ở phần plot đồ thị: mình nghĩ các bạn nên thay "val" bằng "actual", mình nghĩ ý của các bạn là **value** nhưng lúc mới đọc thì mình hiểu nhầm thành **validation**
> * Ở phần kết luận với tập test, mình nghĩ các bạn nên dùng **R-squared** để kết luận để có cái nhìn tốt hơn về mô hình tìm được thay vì **mse**

Cảm ơn ý kiến đóng góp của bạn nha. Mình sẽ cố gắng sửa các lỗi đó trong ngày hôm nay

**Comment by baolongnguyenmac** [comment]
> Xin chào bạn, trước hết thì mình thấy nhóm bạn làm rất tốt vì đã dùng những kiến thức mới và cũng rất phù hợp với bộ dữ liệu trên. Ngay cả việc trực quan hóa kết quả các bạn cũng đã làm rất tốt. Nhưng mình thấy trong phần fit model ở file predict30Days, bạn có dùng epoch = 1 trong khi trước đó ở predict1Days bạn có bước tìm epochs cho mô hình tốt nhất, tại sao qua bên kia bạn không sử dụng lại hoặc tìm lại, chỗ đó mình hơi thắc mắc.

Cảm ơn ý kiến đóng góp của bạn nha. Lý do epoch=1 là trong lần chạy dự đoán 30 ngày, máy mình mất gần 2 tiếng cho 1 epoch :) hiện tại mình vẫn chưa biết cách nào để cho nó chạy nhanh hơn. Nhưng mình có thể chứng minh với 1 tập dữ liệu nhỏ nhỏ là với epoch lớn hơn 1 chút thì sẽ chạy tốt hơn. Hy vọng là mình upload kịp phần chứng minh đó lên git trong hôm nay
